/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class danmaQ_Window */

#ifndef _Included_danmaQ_Window
#define _Included_danmaQ_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     danmaQ_Window
 * Method:    xHacks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_danmaQ_Window_xHacks
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
